#%RAML 1.0 DataType
properties:
  customerID: string
  prefix: string
  suffix: string 
  firstName: string 
  lastName: string
  displayName: string
  address: string
  phoneNo: integer
  email: string
  snn: integer
