#%RAML 1.0 ResourceType
type:
  mine:
  usage: this API is used to get and make any chnages <<resourcePathName>>
  description: provide all information <<resourcePathName>>
  get:
  description: 
                        


  delete:
  post:
  put:
        