#%RAML 1.0 DocumentationItem
title:  Documentaion of  Mine Bank API
content: |

   **MINE Banking API** provides customers and user all the information they need about their balance and the over all services of the bank.[API portal] () click below for more information  (https://anypoint.mulesoft.com/designcenter/designer/#/project/f4604702-4bdc-43bd-9d8e-1491c2bdac48)