#%RAML 1.0 NamedExample
Customer:
  customerID: Af5678
  prefix: Miss
  suffix: Prof 
  firstName: Seble
  lastName: Tadesse
  displayName:  Seble T.
  address: marketstreet
  phoneNo: +12678990886
  email: sE2020@gmail.com
  snn: 4619852247